# Generated by Django 6.0.7 on 2026-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_product_category_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('accessory', 'Accessory'), ('tv,s', 'TV,s')], default='mobile', max_length=50),
        ),
    ]
