# Generated by Django 6.0.7 on 2026-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('accessories', 'Accessories'), ('tv,s', 'TV,s')], default='mobile', max_length=50),
        ),
    ]
